# Generated by Django 6.0.2 on 2026-02-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
