# Generated by Django 6.0.2 on 2026-02-17 03:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_time',
        ),
        migrations.AddField(
            model_name='meal',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='Meal', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_plans.meal')),
            ],
        ),
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
